server:    
    port: 81
    session:
        timeout: 1800

docker:
    #create: /home/docker/docker/createcontainer.sh
    #getport: /home/docker/docker/getport.sh
    
    create: D:/createcontainer.bat
    getport: D:/getport.bat
    
template:
    nginx: nginx.conf.ftl
    serverxml: server.xml.ftl
    
nginx:
    
    
jpa:
# Initialize the schema on startup.
    generate-ddl:  true
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
    hibernate.ddl-auto: none 